import { test, expect } from '@playwright/test';
import { clerk } from '@clerk/testing/playwright';

test.describe('Campaign Flow', () => {
  test('should sign in, navigate to dashboard and create a new campaign', async ({ page }) => {
    test.setTimeout(120000);

    // Mock the backend API calls because we don't want to pollute DB during E2E
    await page.route('/api/campaigns', async route => {
        if (route.request().method() === 'GET') {
            await route.fulfill({ json: { data: [] } });
        } else if (route.request().method() === 'POST') {
            await route.fulfill({ json: { id: 'campaign_123', name: 'E2E Campaign', status: 'DRAFT' }, status: 200 });
        } else {
            await route.continue();
        }
    });

    await page.route('/api/ai/generate', async route => {
        await route.fulfill({ 
            json: { subject: 'E2E Subject', body: 'E2E Body generated by AI' }, 
            status: 200 
        });
    });

    // Go to the home page first to load Clerk without triggering the `<SignIn />` component's own redirect logic
    await page.goto('/', { waitUntil: 'domcontentloaded' });

    // Use Clerk's playwight utility to sign in a bypass testing user
    await clerk.loaded({ page });
    await clerk.signIn({
        page,
        emailAddress: process.env.E2E_CLERK_EMAIL!,
    });

    // Now that the session is established, navigate to the dashboard
    await page.goto('/dashboard', { waitUntil: 'domcontentloaded' });
    await expect(page).toHaveURL(/\/dashboard/, { timeout: 120000 });

    // Check if we arrived successfully
    await expect(page).toHaveTitle(/HyperDrive|Overview|Marketing Agent/i);

    // Verify empty state
    await expect(page.getByText(/No campaigns/i)).toBeVisible({ timeout: 15000 });

    // Click "New Campaign"
    await page.getByRole('link', { name: /New Campaign/i }).click();

    // We should be on the /dashboard/campaigns/new page
    await expect(page).toHaveURL(/\/dashboard\/campaigns\/new/);

    // Fill the campaign setup wizard (Step 1)
    await page.getByLabel(/Campaign Name/i).fill('E2E Campaign');
    await page.getByLabel(/Primary Goal/i).selectOption('Lead Generation');
    await page.getByRole('button', { name: /Continue/i }).click();

    // Step 2
    await page.getByLabel(/Niche/i).fill('Tech startups');
    await page.getByRole('button', { name: /Continue/i }).click();

    // Step 3
    await page.getByLabel(/Core Product/i).fill('We speed up E2E testing');
    
    // Wait for AI Generation simulation
    await page.getByRole('button', { name: /Generate Strategy/i }).click();

    // Wait until Subject comes back from the mocked /api/ai/generate route (Step 4)
    await expect(page.getByLabel(/Generated Subject/i)).toHaveValue('E2E Subject', { timeout: 10000 });
    await expect(page.getByLabel(/Generated Outreach Body/i)).toHaveValue('E2E Body generated by AI');

    // Final Review Step
    await page.getByRole('button', { name: /Save & Deploy Swarm/i }).click();

    // Verify successful creation behavior (probably redirect to dashboard or show success message)
    // Currently the UI checks out and redirects to dashboard
    await expect(page).toHaveURL(/\/(dashboard|dashboard\/campaigns)/);
  });
});